### ISSUE TITLE
About greek letters

### ISSUE THREAD

**Issue by jerome-pouiller** [kragen/xcompose#36]
I didn't see anyway to produce greek letters. Did I miss something? Same question for Hebrew.

Since these alphabets are commonly used mathematical papers, it would be a good idea to add them.

**Comment by clsn** [comment]
Greek is available: check lines approx. 518 et seq. in dotXCompose.  Generally they are `<Multi_key><LETTER><asterisk>`.

No support at the moment for Hebrew, probably at least partly due to the fact that my personal idiosyncratic keyboard has its own idiosyncratic Hebrew layout available, for typing all the letters and vowels and accents etc, so I myself haven't seen much need.  We/you/someone could probably work out some Hebrew bindings, though at some point as alphabets get added they might do better broken out into separate files, and maybe then not worry too much about conflicts, since a person might not need all of them at once.
